version: '3'

services:
  seafile:
    image: frikinet/seafile-arm
    restart: always
    environment:
      - PUID=1005 # Same function as in the linuxserver images
      - PGID=1005 # See https://github.com/linuxserver/docker-swag#user--group-identifiers
    volumes:
      - ./seafile:/shared # <-- Permanent data are stored in the same folder as the compose file by default
    ports:
      - 8000:8000
      - 8082:8082
      - 8083:8083
